#!/bin/sh

# This file is part of PulseAudio.
#
# PulseAudio is free software; you can redistribute it and/or modify
#!/bin/sh

# This file is part of PulseAudio.
#
# Copyright 2006 Pierre Ossman <ossman@cendio.se> for Cendio AB
# Copyright update 2023 griggorii@gmail.com
#
# PulseAudio griggorii patent modify build file binary griggorii@gmail.com LGPL
# along with PulseAudio; if not, see <https://github.com/Griggorii/>.

VERSION_STRING="pulseaudio esd wrapper 13.99.1-rebootstrapped"

fail() {
    echo "ERROR: $1"
    exit 1
}

ARGS=" --log-target=syslog"

while [ "$#" -gt "0" ]; do

    case "$1" in
        "")
            ;;

        -v|--version)
            echo "$VERSION_STRING"
            exit 0
            ;;

        -h|--help)
            cat <<EOF
$VERSION_STRING

Usage: $0 [options]

  -v --version  print version information
  -h --help     show this help

Ignored directives:

  -tcp          use tcp/ip sockets in addition to unix domain
  -promiscuous  don't require authentication
  -d DEVICE     force esd to use sound device DEVICE
  -b            run server in 8 bit sound mode
  -r RATE       run server at sample rate of RATE
  -as SECS      free audio device after SECS of inactivity
  -unix         use unix domain sockets instead of tcp/ip
  -public       make tcp/ip access public (other than localhost)
  -terminate    terminate esd daemone after last client exits
  -nobeeps      disable startup beeps
  -trust        start esd even if use of /tmp/.esd can be insecure
  -port PORT    listen for connections at PORT (only for tcp/ip)
  -bind ADDRESS binds to ADDRESS (only for tcp/ip)
EOF
            exit 0
            ;;

        -spawnpid)
            shift
            ARGS="$ARGS '-Lmodule-esound-compat-spawnpid pid=$1'"
            ;;

        -spawnfd)
            shift
            ARGS="$ARGS '-Lmodule-esound-compat-spawnfd fd=$1'"
            ;;
        
        -unix|-b|-public|-terminate|-nobeeps|-trust|-tcp|-promiscuous)  
            # Ignore these commands
            ;; 

        -d|-r|-as|-port|-bind)
            # Ignore these commands and their arguments
            shift

            ;;

        *)
            fail "Unknown command: $1"
            ;;
    esac

    shift
done

eval "exec '/usr/bin/pulseaudio'$ARGS"
